server:
  port: 8051
  servlet:
    context-path: /api/v1

spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true







