server:
  port: 8051
  servlet:
    context-path: /api/v1


spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5433/TestDB
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update


